---
title: "Coronavirus Analysis"
author: "Lorenzo Braschi"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    # social: ["facebook", "twitter", "linkedin"]
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
remotes::install_github("GuangchuangYu/nCov2019", dependencies = TRUE)

library(shiny)
# library(rvest)
library(flexdashboard)
library(glue)
library(tidyverse)
library(lubridate)
library(rmarkdown)
library(patchwork)
library(ggrepel)
library(nCov2019)

# Set colors
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "firebrick"

# # Countries table
# con_table <- read_html("https://meta.wikimedia.org/wiki/List_of_countries_by_regional_classification") %>%
#   html_node("#content table") %>%
#   html_table() %>%
#   select(1:2) %>%
#   tbl_df() %>%
#   janitor::clean_names() %>%
#   mutate(country = case_when(
#     country == "Congo, The Democratic Republic of the" ~ "Democratic Republic of the Congo",
#     country == "Congo" ~ "Republic of the Congo",
#     country == "Virgin Islands, U.S." ~ "Virgin Islands (U.S.)",
#     country == "Virgin Islands, British" ~ "Virgin Islands",
#     country == "Russian Federation" ~ "Russia",
#     country == "Holy See (Vatican City State)" ~ "Holy See  [Vatican City State]",
#     country == "Tanzania, United Republic of" ~ "Tanzania",
#     country == "Iran, Islamic Republic of" ~ "Iran",
#     country == "Moldova, Republic of" ~ "Moldova",
#     country == "Syrian Arab Republic" ~ "Syria",
#     country == "Côte D'Ivoire" ~ "Côte d'Ivoire",
#     country == "Brunei Darussalam" ~ "Brunei",
#     TRUE ~ country
#   ))


# Theme for plots

theme_set(theme_minimal()+
            theme(legend.position = "",
                  plot.title = element_text(face = "bold", colour = "grey40"),
                  plot.caption = element_text(face = "bold.italic", 
                                              colour = "grey40")
            )
)

all_ncov <- load_nCov2019(lang = "en") %>% 
  .['global'] %>% 
  tbl_df()

  # mutate(
  #   country = case_when(
  #     country == "Republika Severna Makedonija" ~ "Macedonia",
  #     country == "Réunion" ~ "Reunion",
  #     TRUE ~ country
  #   )
  # ) %>%
  # filter(!is.na(country)) %>% 
  # left_join(con_table, by = "country") %>% 
  # mutate(region = ifelse(is.na(region), "None", region))

# mapping_countries <- all_ncov %>% 
#   select(country, region) %>% 
#   count(region, country) %>% 
#   select(1:2) %>% 
#   group_by(region) %>% 
#   nest() 
# 
# mapping_countries <- setNames((mapping_countries$data), mapping_countries$region)


```

Summary
=======================================================================

Sidebar {.sidebar}
-------------------------------------------------------------------------------

The nCov2019 package available from [their GitHub site](https://github.com/GuangchuangYu/nCov2019) provides up-to date information about the COVID-19 epidemic. The data is focused on China, but it contains access to data from the rest of the world as well. They also provide a useful [vignette](https://guangchuangyu.github.io/nCov2019/) in which the common usage of the package is explained.

The nCov2019 package contains data for `r length(unique(all_ncov$country))` countries. 

Select one or more countries to run the analysis. 

```{r}
selectInput("country", 
            label = strong("Select country"), selectize = TRUE,
            choices = sort(unique(all_ncov$country)),
            selected = c("Italy", "Spain"), multiple = TRUE)


```

Select also a range of dates to filter the data. By default, the data range is set from the first case reported in the dataset, December 01 2019, and today,  `r format(Sys.Date(), "%B %d %Y")`. 

```{r}
dateRangeInput("daterange", label = strong("Date Range"),
               start = min(all_ncov$time), 
               end = max(all_ncov$time))


checkboxInput("logaxis", label = strong("Use log axis?"), 
              value = FALSE)

df <- reactive({
  all_ncov %>% 
    filter(country %in% input$country, 
           time >= input$daterange[1], 
           time <= input$daterange[2]) %>% 
    mutate(end_label = ifelse(time == max(time), country, NA))
})



```


Dashboard last updated on **`r format(Sys.Date(), "%B %d %Y")`**. 


Row {data-height=100}
-----------------------------------------------------------------------

### confirmed {.value-box}

```{r}
renderValueBox({
  max_conf <- df() %>%
    filter(time == max(time)) %>%
    summarise(cum_confirm = sum(cum_confirm)) %>%
    pluck("cum_confirm")
  valueBox(
    value = paste(format(max_conf, big.mark = ","), "", sep = " "),
    caption = "Total confirmed cases in the countries selected to date",
    icon = "fas fa-user-md",
    color = confirmed_color
  )
})

```



### death {.value-box}

```{r}
renderValueBox({
  max_dead <- df() %>% 
    filter(time == max(time)) %>% 
    summarise(cum_dead = sum(cum_dead)) %>% 
    pluck("cum_dead")
  valueBox(
    value = paste(format(max_dead, big.mark = ","), "", sep = " "),
    caption = "Total confirmed deaths in the countries selected to date",
    icon = "fas fa-heart",
    color = death_color
  )
})
```





Row
-----------------------------------------------------------------------

### **Cumulative cases per country**

```{r}

renderPlot({
  cumplot <- df() %>% 
    ggplot(aes(time, cum_confirm, color = country))+
    geom_line()+
    geom_label_repel(aes(label = end_label, fill = country), 
                     nudge_x = .1, 
                     nudge_y = .5, 
                     size = 5,
                     color = "white", 
                     show.legend = FALSE
    )+
    labs(x = "",
         caption = glue("Data last updated on {max(df()$time)}"))
  
  if(input$logaxis) {
    cumplot + scale_y_log10("Log number of cases", labels = scales::comma)
  }else{
    cumplot + scale_y_continuous("Number of cases", labels = scales::comma)
  }
  
})


# plotly::plot_ly(data = df_daily) %>%
#   plotly::add_trace(
#     x = ~date,
#     # y = ~active_cum,
#     y = ~confirmed_cum,
#     type = "scatter",
#     mode = "lines+markers",
#     # name = "Active",
#     name = "Confirmed",
#     line = list(color = active_color),
#     marker = list(color = active_color)
#   ) %>%
#   plotly::add_trace(
#     x = ~date,
#     y = ~death_cum,
#     type = "scatter",
#     mode = "lines+markers",
#     name = "Death",
#     line = list(color = death_color),
#     marker = list(color = death_color)
#   ) %>%
#   plotly::add_annotations(
#     x = first.case,
#     y = 1,
#     text = paste("First case"),
#     xref = "x",
#     yref = "y",
#     arrowhead = 5,
#     arrowhead = 3,
#     arrowsize = 1,
#     showarrow = TRUE,
#     ax = -10,
#     ay = -90
#   ) %>%
#   plotly::add_annotations(
#     x = first.death,
#     y = 3,
#     text = paste("First death"),
#     xref = "x",
#     yref = "y",
#     arrowhead = 5,
#     arrowhead = 3,
#     arrowsize = 1,
#     showarrow = TRUE,
#     ax = -90,
#     ay = -90
#   ) %>%
#   plotly::layout(
#     title = "",
#     yaxis = list(title = "Cumulative number of cases"),
#     xaxis = list(title = "Date"),
#     legend = list(x = 0.1, y = 0.9),
#     hovermode = "compare"
#   )
```

### **Cumulative deaths per country**

```{r}
renderPlot({
  deathplot <- df() %>% 
    ggplot(aes(time, cum_dead, color = country))+
    geom_line()+
    geom_label_repel(aes(label = end_label, fill = country), 
                     nudge_x = .1, 
                     nudge_y = .5, 
                     size = 5,
                     color = "white", 
                     show.legend = FALSE
    )+
    labs(x = "",
         caption = glue("Data last updated on {max(df()$time)}"))
  
  
  if(input$logaxis) {
    deathplot + scale_y_log10("Log number of deaths", labels = scales::comma)
  }else{
    deathplot + scale_y_continuous("Number of deaths", labels = scales::comma)
  }
  
})

```


Epidemic curves
=======================================================================

Sidebar {.sidebar}
-------------------------------------------------------------------------------

```{r}
selectInput("singlecountry", 
            label = strong("Epidemic curves country"), 
            choices = sort(unique(all_ncov$country)),
            selected = "Spain", 
            multiple = FALSE)

dateInput("dateEpi", label = strong("Min date"),
          value = Sys.Date() %m-% months(2) %>% floor_date(unit = "month"),
          autoclose = T,
          min = min(all_ncov$time), 
          max = max(all_ncov$time))


df_daily <- reactive({
  all_ncov %>% 
    arrange(country, time) %>% 
    group_by(country) %>% 
    mutate(
      cases_confirm = cum_confirm - lag(cum_confirm), 
      cases_recover = cum_heal - lag(cum_heal), 
      cases_dead = cum_dead - lag(cum_dead)
    ) %>% 
    # Remove empty rows; just removing if empty confirm should be enough
    filter(!is.na(cases_confirm), 
           time >= input$dateEpi)
})



```


Row {.tabset data-height=800} 
-------------------------------------

### **Epidemic curves** 

```{r}
renderPlot({
  baseEpiplot <- df_daily() %>%
    filter(country == input$singlecountry) %>% 
    mutate(seconddif = cases_confirm - lag(cases_confirm)) %>% 
    ggplot(aes(time, cases_confirm))+
    scale_y_continuous(labels = scales::comma)+
    labs(x = "")
  
  p1 <- baseEpiplot + 
    geom_bar(stat = "identity", fill = confirmed_color)+
    labs(y = "Number of new cases", 
         title = glue("{input$singlecountry}"))
  
  p2 <- baseEpiplot +
    geom_hline(yintercept = 0, color = "grey50", linetype = 2)+
    geom_line(aes(y = seconddif), color = confirmed_color)+
    # geom_rect(aes(xmin = min(time), xmax = max(time),
    #               ymin = min(seconddif), ymax = 0), fill = "green", alpha = .25)+
    labs(y = "Diff cases", 
         title = "New cases acceleration rate")+
    theme(panel.grid = element_blank())
  
  p1 / p2 + plot_layout(heights = c(3,1))
  
})



```




### **Casualties**

```{r daily_summary}
renderPlot({
  df_daily() %>% 
    filter(country == input$singlecountry) %>% 
    ggplot(aes(time, cases_dead))+
    geom_bar(stat = "identity", fill = death_color)+
    scale_y_continuous(labels = scales::comma)+
    labs(x = "",
         y = "Number of deceased"
    )
})
```

Column {data.height=200}
-------------------------------------

### **Another plot**


Map
=======================================================================

### **World map of cases** (*use + and - icons to zoom in/out*)

```{r}
# # map tab added by Art Steinmetz
# library(leaflet)
# library(leafpop)
# library(purrr)
# cv_data_for_plot <- coronavirus %>%
#   # dplyr::filter(Country.Region == params$country) %>%
#   dplyr::filter(cases > 0) %>%
#   dplyr::group_by(Country.Region, Province.State, Lat, Long, type) %>%
#   dplyr::summarise(cases = sum(cases)) %>%
#   dplyr::mutate(log_cases = 2 * log(cases)) %>%
#   dplyr::ungroup()
# cv_data_for_plot.split <- cv_data_for_plot %>% split(cv_data_for_plot$type)
# pal <- colorFactor(c("orange", "red", "green"), domain = c("confirmed", "death", "recovered"))
# map_object <- leaflet() %>% addProviderTiles(providers$Stamen.Toner)
# names(cv_data_for_plot.split) %>%
#   purrr::walk(function(df) {
#     map_object <<- map_object %>%
#       addCircleMarkers(
#         data = cv_data_for_plot.split[[df]],
#         lng = ~Long, lat = ~Lat,
#         #                 label=~as.character(cases),
#         color = ~ pal(type),
#         stroke = FALSE,
#         fillOpacity = 0.8,
#         radius = ~log_cases,
#         popup = leafpop::popupTable(cv_data_for_plot.split[[df]],
#           feature.id = FALSE,
#           row.numbers = FALSE,
#           zcol = c("type", "cases", "Country.Region", "Province.State")
#         ),
#         group = df,
#         #                 clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
#         labelOptions = labelOptions(
#           noHide = F,
#           direction = "auto"
#         )
#       )
#   })
# 
# map_object %>%
#   addLayersControl(
#     overlayGroups = names(cv_data_for_plot.split),
#     options = layersControlOptions(collapsed = FALSE)
#   )
```





About
=======================================================================

<!-- **The Coronavirus Dashboard: the case of Poland** -->

<!-- This Coronavirus dashboard: the case of Poland provides an overview of the 2019 Novel Coronavirus COVID-19 (2019-nCoV) epidemic for Poland. This dashboard is built with R using the R Makrdown framework and was adapted from this [dashboard](https://www.antoinesoetewey.com/files/coronavirus-dashboard.html) by Antoine Soetewey, which in turn was inspired by this other [dashboard](https://ramikrispin.github.io/coronavirus_dashboard/){target="_blank"} by Rami Krispin. -->

<!-- **Code** -->

<!-- The code behind this dashboard is available on [GitHub](https://github.com/AntoineSoetewey/coronavirus_dashboard){target="_blank"}. -->

<!-- **Data** -->

<!-- The input data for this dashboard is the dataset available from the [`{coronavirus}`](https://github.com/RamiKrispin/coronavirus){target="_blank"} R package. Make sure to download the development version of the package to have the latest data: -->

<!-- ``` -->
<!-- install.packages("devtools") -->
<!-- devtools::install_github("RamiKrispin/coronavirus") -->
<!-- ``` -->

<!-- The data and dashboard are refreshed on a daily basis. -->

<!-- The raw data is pulled from the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE) Coronavirus [repository](https://github.com/RamiKrispin/coronavirus-csv){target="_blank"}. -->

<!-- **Contact** -->

<!-- For any question or feedback, you can [contact me](https://www.statsandr.com/contact/). More information about this dashboard can be found in this [article](https://www.statsandr.com/blog/how-to-create-a-simple-coronavirus-dashboard-specific-to-your-country-in-r/). -->

<!-- **Update** -->




<!-- *Go back to [www.statsandr.com](https://www.statsandr.com/) (blog) or [www.antoinesoetewey.com](https://www.antoinesoetewey.com/) (personal website)*. -->
